name: Check for Hardcoded IPs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run IP Check
        uses: dprakash2101/hardcoded-ip-check@main  # Ensure the repository name is correct
        with:
          directories: 'src, app, config'  # Specify directories to check
